[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:Xvfb]
command=Xvfb :1 -screen 0 %(ENV_RESOLUTION)s
autorestart=true
priority=100

[program:x11vnc]
command=x11vnc -display :1 -nopw -listen 0.0.0.0 -xkb -forever -shared -rfbport 5900
autorestart=true
priority=200
depends_on=Xvfb

[program:novnc]
command=websockify --web=/usr/share/novnc 6080 localhost:5900
autorestart=true
priority=300
depends_on=x11vnc

[program:app]
command=/startup.sh
autorestart=false
priority=400
stdout_logfile=/var/log/supervisor/app.log
stderr_logfile=/var/log/supervisor/app-error.log
